/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lester.sad;

/**
 *
 * @author user
 */
public class Certificate extends javax.swing.JFrame {

    /**
     * Creates new form Certificate
     */
    public Certificate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setUndecorated(true);
        jFrame1.setOpacity(0.9F);
        jFrame1.getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Gabriola", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CERTIFICATES");
        jFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 10, 270, 50);

        jLabel12.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Request For: ");
        jFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 70, 90, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marriage Certificate", "Baptismal Certificate", "First Communion Certificate", "Others.." }));
        jFrame1.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(140, 70, 180, 30);

        jLabel16.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Note: Mark with * is required");
        jFrame1.getContentPane().add(jLabel16);
        jLabel16.setBounds(380, 400, 280, 20);

        jLabel17.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Adress");
        jFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(380, 180, 60, 31);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setOpaque(false);
        jFrame1.getContentPane().add(jTextField5);
        jTextField5.setBounds(440, 180, 160, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        jFrame1.getContentPane().add(jLabel18);
        jLabel18.setBounds(610, 190, 40, 14);

        jButton3.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jButton3.setText("Pay");
        jFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(490, 340, 140, 50);

        jLabel19.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Client No. ");
        jFrame1.getContentPane().add(jLabel19);
        jLabel19.setBounds(370, 80, 60, 31);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        jFrame1.getContentPane().add(jLabel20);
        jLabel20.setBounds(610, 90, 40, 14);

        jButton4.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jButton4.setText("Process Request");
        jFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(330, 340, 140, 50);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setOpaque(false);
        jFrame1.getContentPane().add(jTextField6);
        jTextField6.setBounds(440, 130, 160, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        jFrame1.getContentPane().add(jLabel21);
        jLabel21.setBounds(610, 140, 40, 14);

        jLabel22.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Full Name");
        jFrame1.getContentPane().add(jLabel22);
        jLabel22.setBounds(370, 130, 60, 31);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setOpaque(false);
        jFrame1.getContentPane().add(jTextField7);
        jTextField7.setBounds(440, 80, 160, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel23.setText("Requirements:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(12, 13, 80, 31);

        jCheckBox11.setText("jCheckBox1");
        jCheckBox11.setOpaque(false);
        jPanel2.add(jCheckBox11);
        jCheckBox11.setBounds(12, 51, 81, 23);

        jCheckBox12.setText("jCheckBox2");
        jCheckBox12.setOpaque(false);
        jPanel2.add(jCheckBox12);
        jCheckBox12.setBounds(170, 51, 81, 23);

        jCheckBox13.setText("jCheckBox3");
        jCheckBox13.setOpaque(false);
        jPanel2.add(jCheckBox13);
        jCheckBox13.setBounds(12, 92, 81, 23);

        jCheckBox14.setText("jCheckBox3");
        jCheckBox14.setOpaque(false);
        jPanel2.add(jCheckBox14);
        jCheckBox14.setBounds(170, 92, 81, 23);

        jCheckBox15.setText("jCheckBox3");
        jCheckBox15.setOpaque(false);
        jPanel2.add(jCheckBox15);
        jCheckBox15.setBounds(12, 142, 81, 23);

        jCheckBox16.setText("jCheckBox3");
        jCheckBox16.setOpaque(false);
        jPanel2.add(jCheckBox16);
        jCheckBox16.setBounds(170, 142, 81, 23);

        jCheckBox17.setText("jCheckBox3");
        jCheckBox17.setOpaque(false);
        jPanel2.add(jCheckBox17);
        jCheckBox17.setBounds(12, 195, 81, 23);

        jCheckBox18.setText("jCheckBox3");
        jCheckBox18.setOpaque(false);
        jPanel2.add(jCheckBox18);
        jCheckBox18.setBounds(170, 195, 81, 23);

        jCheckBox19.setText("jCheckBox3");
        jCheckBox19.setOpaque(false);
        jPanel2.add(jCheckBox19);
        jCheckBox19.setBounds(170, 236, 81, 23);

        jCheckBox20.setText("jCheckBox3");
        jCheckBox20.setOpaque(false);
        jPanel2.add(jCheckBox20);
        jCheckBox20.setBounds(12, 236, 81, 23);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Backgrounds.png"))); // NOI18N
        jPanel2.add(jLabel24);
        jLabel24.setBounds(-10, -120, 1330, 600);

        jFrame1.getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 120, 290, 290);

        jLabel25.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Full Name");
        jFrame1.getContentPane().add(jLabel25);
        jLabel25.setBounds(370, 130, 60, 31);

        jTextField8.setOpaque(false);
        jFrame1.getContentPane().add(jTextField8);
        jTextField8.setBounds(440, 130, 160, 30);

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CHURCH RESERVATION SYSTEM");
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setText("REQUEST FOR:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 200, 200, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Crtificates.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 390, 100);

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Marriage Certificate", "Baptismal Certificate", "Funeral Certificate", " " }));
        jComboBox1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 200, 240, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Note: Mark with * is required");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(850, 490, 260, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("    Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 430, 160, 40);

        jTextField1.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(810, 430, 330, 40);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1150, 430, 30, 40);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setText("Pay");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 204)));
        getContentPane().add(jButton2);
        jButton2.setBounds(910, 580, 240, 50);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText(" Client No. :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 310, 160, 40);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1150, 310, 20, 40);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Process Request");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 204)));
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 580, 240, 50);

        jTextField4.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField4.setOpaque(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(810, 370, 330, 40);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1150, 370, 30, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText(" Full Name :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(650, 370, 160, 40);

        jTextField2.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(810, 310, 330, 40);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "REQUIREMENTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setOpaque(false);
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(60, 100, 140, 31);

        jCheckBox2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setOpaque(false);
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(250, 100, 140, 31);

        jCheckBox3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.setOpaque(false);
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(60, 150, 140, 31);

        jCheckBox4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox4.setText("jCheckBox3");
        jCheckBox4.setOpaque(false);
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(250, 150, 140, 31);

        jCheckBox5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox5.setText("jCheckBox3");
        jCheckBox5.setOpaque(false);
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(60, 200, 140, 31);

        jCheckBox6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox6.setText("jCheckBox3");
        jCheckBox6.setOpaque(false);
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(250, 200, 140, 31);

        jCheckBox7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox7.setText("jCheckBox3");
        jCheckBox7.setOpaque(false);
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(60, 240, 140, 31);

        jCheckBox8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox8.setText("jCheckBox3");
        jCheckBox8.setOpaque(false);
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(250, 240, 140, 31);

        jCheckBox9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox9.setText("jCheckBox3");
        jCheckBox9.setOpaque(false);
        jPanel1.add(jCheckBox9);
        jCheckBox9.setBounds(250, 290, 140, 31);

        jCheckBox10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jCheckBox10.setText("jCheckBox3");
        jCheckBox10.setOpaque(false);
        jPanel1.add(jCheckBox10);
        jCheckBox10.setBounds(60, 290, 140, 31);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Backgrounds.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(620, -120, 700, 510);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 280, 470, 350);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Backgrounds.png"))); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(0, 0, 1420, 750);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(1130, 300, 40, 14);

        setSize(new java.awt.Dimension(1345, 787));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Certificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Certificate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
