/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lester.sad;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;



/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        user.requestFocus();
        pass.selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CHURCH RESERVATION SYSTEM");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        user.setFont(new java.awt.Font("Century Gothic", 2, 20)); // NOI18N
        user.setForeground(new java.awt.Color(153, 153, 153));
        user.setText(" Username");
        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userKeyTyped(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(70, 160, 330, 40);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/LoginButton.png"))); // NOI18N
        login.setBorder(null);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(160, 410, 220, 70);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/CancelButton.png"))); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(160, 490, 220, 70);

        pass.setFont(new java.awt.Font("Century Gothic", 2, 20)); // NOI18N
        pass.setForeground(new java.awt.Color(153, 153, 153));
        pass.setText(" Password");
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        getContentPane().add(pass);
        pass.setBounds(70, 250, 330, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Password.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 220, 460, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Username.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 150, 460, 70);

        info.setForeground(new java.awt.Color(255, 0, 0));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setText("jLabel4");
        getContentPane().add(info);
        info.setBounds(50, 330, 450, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/LogIn.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 557, 630);

        setSize(new java.awt.Dimension(574, 668));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
            user.setText("");
             user.setForeground(Color.BLACK);
    }//GEN-LAST:event_userMouseClicked

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_userKeyTyped

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
            pass.setText("");
             pass.setForeground(Color.BLACK);
    }//GEN-LAST:event_passMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
      
        
        
        
         int x = JOptionPane.showConfirmDialog(this, "Are you sure you want to Cancel?", "Cancel", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            this.setVisible(false);
            System.exit(0);
        } else {
            this.requestFocus();
        }
       
        
        
    }//GEN-LAST:event_cancelActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
          
        
         String username = user.getText();
         String password = pass.getText();
         
         
    Connection con = null;
    ResultSet res;
    ResultSet res2;
    int attempts = 0;
    info.setText(" ");
    
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql:///stjamesparishchurch", "root", "");
            if (!con.isClosed()) {
            }
        } catch (ClassNotFoundException | SQLException error) {
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
     
         
         
        
         if (username.isEmpty() == true) {
            JOptionPane.showMessageDialog(rootPane, "Sorry! Username Cannot be Empty Thankyou! ");
            user.setBorder(new LineBorder(Color.red));
            user.requestFocus();
           
        } else if (password.isEmpty() == true) {
            JOptionPane.showMessageDialog(rootPane, "Sorry! Password Cannot be Empty Thankyou! ");
            pass.setBorder(new LineBorder(Color.red));
            pass.requestFocus();
          
            
        } else if (username.length() <5) {
           JOptionPane.showMessageDialog(rootPane, "Sorry! Username too short ");
            user.setBorder(new LineBorder(Color.red));
            user.selectAll();
            user.requestFocus();
        } else if (password.length() < 5) {
            JOptionPane.showMessageDialog(rootPane, "Sorry! Password too short ");
            pass.setBorder(new LineBorder(Color.red));
            pass.selectAll();
            pass.requestFocus();
        } else {
            
            try {
                
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql:///stjamesparishchurch", "root", "");
            if (!con.isClosed()) {
            }
                
                Statement st = con.createStatement();
                String status1="blocked";
                String block = "Select * from blocked_user where Username = '"+username+"'  ";
                res2 =st.executeQuery(block);   
   
             
      while(res2.next()){     
         String userName=res2.getString(1);
          if(userName.equals(username)){
          JOptionPane.showMessageDialog(rootPane, "Sorry! Your Account is Blocked by the System, Please Contact the Admin");
                 
          info.setText(""); 
                        
                 return;
                   
              }

      }
   
             
      while(res2.next()){     
         String userName=res2.getString(1);
          if(userName.equals(username)){
          info.setText("Sorry, Your Account is Blocked by the System. Thankyou and GodBless! ");
//                         error1.setText("please contact the administrator to have");  
//                         error1.setText("your account unlocked."); 
//                         error1.setText(""); 
                        
                 return;
                   
              }

      }
      
                String query1 = "Select * from users where Username= '" + username + "'";
                res = st.executeQuery(query1);
                while (res.next()) {
                    String user1 = res.getString(1);
                    String pass1 = res.getString(2);
                    String getuser = user.getText();
                    String getpass = pass.getText();
                    if (user1.equals(getuser) && pass1.equals(getpass)) {
                        
                        if(res.getString(3).equals("Administrator")){
                        System.out.print("LOGIN SUCESS");
                        this.setVisible(false);
                        new Home().setVisible(true);
          
                    }       
                   if(res.getString(3).equals("Secretary")){
                   System.out.print("LOGIN SUCESS");
                   this.setVisible(false);
                   new Home().setVisible(true);

                   }
                     
                    } else {
                        
                        JOptionPane.showMessageDialog(this, "Sorry, your account is not registered contact the administrator to have one. Thankyou and Godbless.");
                        attempts++;
                    }
                }
                
                if (attempts == 1) {
                    info.setText("(1/3) Remaining Attempts.");
                }
              else if (attempts == 2) {
                    info.setText("(2/3) Remaining Attempts.");
                }
              else{
                   JOptionPane.showMessageDialog(rootPane, "(3/3) Sorry You'd reached the maximuim attempts to login in the System Your account will be blocked. Please Contact The Admin ");
                   
                  
                    String query = "INSERT INTO blocked_user values ('" + status1 + "','" + status1 + "')";
                    st.executeUpdate(query);
              
                
                    System.out.print("yes!");
                }
                
            }catch(Exception e){
               info.setText(e.getMessage());
                        

                
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
