/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lester.sad;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Records extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet res;
    PreparedStatement pre;

    /**
     * Creates new form Records
     */
    public Records() {
        initComponents();
        dbconnect();
        database();
    }

    public void database() {
        try {
            stmt = conn.createStatement();
            res = stmt.executeQuery("SELECT * FROM emp");
            table.setModel(DbUtils.resultSetToTableModel(res));
        } catch (Exception er) {
            System.out.println("Error: " + er.getMessage());
        }
    }

    public void dbconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sad", "root", "");
            System.out.println("Connected...");
        } catch (SQLException e) {
            System.out.println("Error: " + e.getNextException());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cboview = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CHURCH RESERVATION SYSTEM");
        getContentPane().setLayout(null);

        jScrollPane1.setOpaque(false);

        table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Client No", "Category", "Client Name", "Date Of Event", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setEnabled(false);
        table.setOpaque(false);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 230, 1080, 350);

        cboview.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cboview.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Here", " ", "Employee ID", "First Name", "Middle Name", "Last Name", "Gender", "Position", " " }));
        cboview.setBorder(new javax.swing.border.MatteBorder(null));
        cboview.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboviewItemStateChanged(evt);
            }
        });
        cboview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboviewActionPerformed(evt);
            }
        });
        getContentPane().add(cboview);
        cboview.setBounds(1000, 170, 200, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Rcord.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 370, 100);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 204)));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(960, 620, 240, 50);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setText("  View Records By : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 170, 290, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/Backgrounds.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1330, 750);

        setSize(new java.awt.Dimension(1343, 789));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboviewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboviewItemStateChanged
        // TODO add your handling code here:
        try {
            if (cboview.getSelectedItem() == "Employee ID") {
                try {
                    stmt = conn.createStatement();
                    res = stmt.executeQuery("SELECT * FROM emp ORDER BY emp_no ASC");
                    table.setModel(DbUtils.resultSetToTableModel(res));
                } catch (Exception er) {
                    System.out.println("Error: " + er.getMessage());
                }
            }
            if (cboview.getSelectedItem() == "First Name") {
                try {
                    stmt = conn.createStatement();
                    res = stmt.executeQuery("SELECT * FROM emp ORDER BY firstname ASC");
                    table.setModel(DbUtils.resultSetToTableModel(res));
                } catch (Exception er) {
                    System.out.println("Error: " + er.getMessage());
                }
            }
            if (cboview.getSelectedItem() == "Middle Name") {
                try {
                    stmt = conn.createStatement();
                    res = stmt.executeQuery("SELECT * FROM emp ORDER BY middlename ASC");
                    table.setModel(DbUtils.resultSetToTableModel(res));
                } catch (Exception er) {
                    System.out.println("Error: " + er.getMessage());
                }
            }
            if (cboview.getSelectedItem() == "Last Name") {
                try {
                    stmt = conn.createStatement();
                    res = stmt.executeQuery("SELECT * FROM emp ORDER BY lastname ASC");
                    table.setModel(DbUtils.resultSetToTableModel(res));
                } catch (Exception er) {
                    System.out.println("Error: " + er.getMessage());
                }
            }
            if (cboview.getSelectedItem() == "Gender") {
                try {
                    stmt = conn.createStatement();
                    res = stmt.executeQuery("SELECT * FROM emp ORDER BY gender DESC");
                    table.setModel(DbUtils.resultSetToTableModel(res));
                } catch (Exception er) {
                    System.out.println("Error: " + er.getMessage());
                }
            }
            if (cboview.getSelectedItem() == "Position") {
                try {
                    stmt = conn.createStatement();
                    res = stmt.executeQuery("SELECT * FROM emp ORDER BY position");
                    table.setModel(DbUtils.resultSetToTableModel(res));
                } catch (Exception er) {
                    System.out.println("Error: " + er.getMessage());
                }
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cboviewItemStateChanged

    private void cboviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Records().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboview;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
