/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lester.sad;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author user
 */
public class Reservations extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet res;
    PreparedStatement pre, pre1;
    int rawRandomNumber;

    /**
     * Creates new form Reservations
     */
    public Reservations() {
        initComponents();
        dbconnect();
        generate();
        clientno.setText(String.valueOf(rawRandomNumber));
        for (int i = 1; i < 32; i++) {
            day.addItem(i);
        }
        hehe();
    }

    public void hehe() {
        try {
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            //get current date time with Date()
            Date date = new Date();
            // Time
            Calendar cal = Calendar.getInstance();
            cal.getTime();
            DateFormat sdf = new SimpleDateFormat("hh:mm");
            //
            stmt = conn.createStatement();
            String cno = clientno.getText(),
                    cname = clientname.getText().trim(),
                    address = add.getText().trim(),
                    contactnum = contact.getText().trim(),
                    dateout = month.getSelectedItem().toString() + " " + day.getSelectedItem().toString()
                    + " " + year.getSelectedItem().toString(),
                    timeout = hour.getText().trim() + ":" + min.getText().trim() + " "
                    + datetime.getSelectedItem().toString(),
                    datein = dateFormat.format(date),
                    timein = sdf.format(cal.getTime());

            if (dateout.equals(res.getString("dateout")) && timeout.equals(res.getString("timeout"))) {
                String sql = "DELETE FROM reserved WHERE client_no = '" + cno + "' ";
                pre1 = conn.prepareStatement(sql);
                pre1.executeUpdate();

            }
        } catch (Exception er) {
            System.out.println("Error: " + er.getMessage());
        }
    }

    public void dbconnect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sad", "root", "");
            System.out.println("Connected...");
        } catch (SQLException e) {
            System.out.println("Error: " + e.getNextException());
            e.printStackTrace();
        }
    }

    public void generate() {
        int min = 1;
        int max = 29999;
        for (int i = 0; i < 29998; i++) {
            rawRandomNumber = (int) (Math.random() * (max - min + 1)) + min;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbocateg = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clientno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        month = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        day = new javax.swing.JComboBox();
        btnres = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        hour = new javax.swing.JTextField();
        datetime = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        clientname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.9F);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESERVATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 250, 40);

        cbocateg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose here", "Baptismal", "Marriage", "Funeral" }));
        cbocateg.setOpaque(false);
        cbocateg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbocategItemStateChanged(evt);
            }
        });
        cbocateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocategActionPerformed(evt);
            }
        });
        getContentPane().add(cbocateg);
        cbocateg.setBounds(110, 70, 170, 40);

        jLabel3.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 80, 41);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Requirements");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 2, 101, 41);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(119, 13, 11, 22);

        jCheckBox1.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setEnabled(false);
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(12, 45, 230, 23);

        jCheckBox2.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setEnabled(false);
        jCheckBox2.setOpaque(false);
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(10, 170, 220, 23);

        jCheckBox3.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.setEnabled(false);
        jCheckBox3.setOpaque(false);
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(10, 100, 230, 23);

        jCheckBox4.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("jCheckBox4");
        jCheckBox4.setEnabled(false);
        jCheckBox4.setOpaque(false);
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(10, 230, 210, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 120, 250, 270);

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 300, 40, 31);

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Client No. : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 80, 80, 30);

        clientno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clientno.setEnabled(false);
        clientno.setOpaque(false);
        getContentPane().add(clientno);
        clientno.setBounds(440, 80, 140, 30);

        jLabel7.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Client Full Name : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 120, 110, 40);

        add.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add.setOpaque(false);
        getContentPane().add(add);
        add.setBounds(440, 160, 140, 30);

        jLabel8.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 160, 80, 30);

        jLabel9.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact Number:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 200, 120, 20);

        min.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        min.setText("    Min");
        min.setOpaque(false);
        getContentPane().add(min);
        min.setBounds(460, 300, 50, 30);

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(month);
        month.setBounds(340, 250, 120, 30);

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2015" }));
        getContentPane().add(year);
        year.setBounds(550, 250, 80, 30);

        day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day" }));
        getContentPane().add(day);
        day.setBounds(470, 250, 70, 30);

        btnres.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnres.setText("RESERVE");
        btnres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresActionPerformed(evt);
            }
        });
        getContentPane().add(btnres);
        btnres.setBounds(510, 360, 110, 40);

        jLabel10.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Note: Mark with * is required");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 410, 220, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(590, 210, 11, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(590, 160, 20, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(590, 90, 40, 14);

        jLabel16.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(300, 250, 40, 31);

        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setOpaque(false);
        getContentPane().add(contact);
        contact.setBounds(440, 200, 140, 30);

        hour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hour.setText("   Hr");
        hour.setOpaque(false);
        getContentPane().add(hour);
        hour.setBounds(400, 300, 50, 30);

        datetime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a.m", "p.m" }));
        getContentPane().add(datetime);
        datetime.setBounds(520, 300, 70, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(590, 120, 20, 30);

        clientname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clientname.setOpaque(false);
        getContentPane().add(clientname);
        clientname.setBounds(440, 120, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churchreservationmanagementsystem/14448952344_20b9135bbf_z.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        setSize(new java.awt.Dimension(640, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbocategItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbocategItemStateChanged
        // TODO add your handling code here:
        if (cbocateg.getSelectedItem().toString() == "Baptismal") {
            jCheckBox1.setText(null);
            jCheckBox2.setText(null);
            jCheckBox3.setText(null);
            jCheckBox4.setText(null);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jCheckBox3.setSelected(true);
            jCheckBox4.setSelected(true);
            jCheckBox1.setText("Birth Certificate");
            jCheckBox2.setText("Parent's Marriage Contract");
            jCheckBox3.setText("Certificate of Sponsor");
            jCheckBox4.setText("Birth Certificate");
        }
        if (cbocateg.getSelectedItem().toString() == "Marriage") {
            jCheckBox1.setText(null);
            jCheckBox2.setText(null);
            jCheckBox3.setText(null);
            jCheckBox4.setText(null);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jCheckBox3.setSelected(true);
            jCheckBox4.setSelected(true);
            jCheckBox1.setText("Baptismal Certificates");
            jCheckBox2.setText("Marriage License");
            jCheckBox3.setText("Confirmation Certificates");
            jCheckBox4.setText("Sponsors");
        }
        if (cbocateg.getSelectedItem().toString() == "Funeral") {
            jCheckBox1.setText(null);
            jCheckBox2.setText(null);
            jCheckBox3.setText(null);
            jCheckBox4.setText(null);
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(true);
            jCheckBox3.setSelected(true);
            jCheckBox4.setSelected(true);
            jCheckBox1.setText("Obituary");
            jCheckBox2.setText("Order of Service");
            jCheckBox3.setText("Miscellaneous");
            jCheckBox4.setText("Donation & Costs");
        }
        if (cbocateg.getSelectedItem() == "Choose here") {
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox1.setText("jCheckBox1");
            jCheckBox2.setText("jCheckBox2");
            jCheckBox3.setText("jCheckBox3");
            jCheckBox4.setText("jCheckBox4");
        }
    }//GEN-LAST:event_cbocategItemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cbocategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbocategActionPerformed

    private void btnresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresActionPerformed
        // TODO add your handling code here:
        try {
            // Restrictions
            // Date
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            //get current date time with Date()
            Date date = new Date();
            // Time
            Calendar cal = Calendar.getInstance();
            cal.getTime();
            DateFormat sdf = new SimpleDateFormat("hh:mm");
            //
            stmt = conn.createStatement();
            String cno = clientno.getText(),
                    cname = clientname.getText().trim(),
                    address = add.getText().trim(),
                    contactnum = contact.getText().trim(),
                    dateout = month.getSelectedItem().toString() + " " + day.getSelectedItem().toString()
                    + " " + year.getSelectedItem().toString(),
                    timeout = hour.getText().trim() + ":" + min.getText().trim() + " "
                    + datetime.getSelectedItem().toString(),
                    datein = dateFormat.format(date),
                    timein = sdf.format(cal.getTime());
            String sql = "INSERT INTO reserved"
                    + " VALUES('" + cno + "','" + cname + "','" + address + "','" + contactnum + "','" + datein + "','" + dateout + "','" + timein + "','" + timeout + "')";
            pre = conn.prepareStatement(sql);
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully reserved!");
            this.setVisible(false);
            new Payment().setVisible(true);

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservations().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JButton btnres;
    private javax.swing.JComboBox cbocateg;
    private javax.swing.JTextField clientname;
    private javax.swing.JTextField clientno;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox datetime;
    private javax.swing.JComboBox day;
    private javax.swing.JTextField hour;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField min;
    private javax.swing.JComboBox month;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
